### ISSUE TITLE
Use fixed time comparison

### ISSUE THREAD

**Issue by moderndeveloperllc** [Monofraps/angular-node-hmac-example#2]
I see in the node.js server that you are [comparing the hashes](https://github.com/Monofraps/angular-node-hmac-example/blob/master/server/hmac.js#L146) with a simple comparison. You might want to look into using a fixed-time comparison like [wolfeidau/ofuda](https://github.com/wolfeidau/ofuda/blob/master/lib/ofuda.js#L222) is doing using the cryptiles library, or just replication gthe code yourself. This helps prevent time-based attacks on the hash.

**Comment by Monofraps** [comment]
Thanks for the advice. I'll look into it :)

**Comment by moderndeveloperllc** [comment]
Quick question: Where are you getting `localStorage`? I was under the impression that a wrapper was need to access that. Is it in one of the dependencies?

**Comment by Monofraps** [comment]
You don't need a wrapper as far as I know (at least not in Chrome). I think it's an HTML5 addition if I'm not mistaking.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API
